sudo: false

language: python

cache:
  directories:
  - node_modules
  - pebble-dev

script:
- ./node_modules/.bin/gulp
- cmake -DTRAVIS=ON . && make
- npm test
- ctest -V

before_install:
- sh before_install.sh

install:
- make --directory=cmocka-1.0.1/build && make install --directory=cmocka-1.0.1/build
- pip install --install-option="--no-cython-compile" cython
- virtualenv --no-site-packages pebble-dev/${PEBBLE_SDK}/.env
- source pebble-dev/${PEBBLE_SDK}/.env/bin/activate
- pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt
- deactivate
- nvm install 5.3.0
- npm install
- export PATH=$(pwd)/pebble-dev/${PEBBLE_SDK}/bin:$PATH
- touch pebble-dev/NO_TRACKING
- yes | pebble sdk install 3.8.2

env:
  global:
  - PEBBLE_SDK=pebble-sdk-4.0-linux64
