sudo: false

language: python

script:
- ./node_modules/.bin/gulp
- npm test
- cd build
- cmake -DTRAVIS=ON ..
- make
- make test

before_install:
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk2/${PEBBLE_SDK}.tar.gz -O PebbleSDK.tar.gz
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk/arm-cs-tools-ubuntu-universal.tar.gz
- mkdir pebble-dev
- tar -zxf PebbleSDK.tar.gz -C pebble-dev
- tar -zxf arm-cs-tools-ubuntu-universal.tar.gz -C pebble-dev/${PEBBLE_SDK}
- wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
- tar -xvf cmocka-1.0.1.tar.xz
- cd cmocka-1.0.1
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=/home/travis/build/xdjinnx/Slebble/cmocka -DCMAKE_BUILD_TYPE=Debug ..
- make
- make install
- cd ../..

install:
- nvm install 4.1
- pip install --install-option="--no-cython-compile" cython
- pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt
- npm install
- export PATH=$(pwd)/pebble-dev/${PEBBLE_SDK}/bin:$PATH
- touch pebble-dev/NO_TRACKING


env:
  global:
  - PEBBLE_SDK=PebbleSDK-3.4
