sudo: false

language: python

script:
- ./node_modules/.bin/gulp
- cmake -DTRAVIS=ON . && make
- npm test
- ctest -V

before_install:
- wget https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/${PEBBLE_SDK}.tar.bz2 -O PebbleSDK.tar.bz2
- mkdir pebble-dev
- tar -xvjf PebbleSDK.tar.bz2 -C pebble-dev
- wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
- tar -xvf cmocka-1.0.1.tar.xz
- mkdir cmocka-1.0.1/build
- cmake -DCMAKE_INSTALL_PREFIX=/home/travis/build/xdjinnx/Slebble/cmocka -DCMAKE_BUILD_TYPE=Debug -Bcmocka-1.0.1/build -Hcmocka-1.0.1

install:
- make --directory=cmocka-1.0.1/build && make install --directory=cmocka-1.0.1/build
- pip install --install-option="--no-cython-compile" cython
- virtualenv --no-site-packages pebble-dev/${PEBBLE_SDK}/.env
- source pebble-dev/${PEBBLE_SDK}/.env/bin/activate
- pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt
- deactivate
- nvm install 5.3.0
- npm install
- export PATH=$(pwd)/pebble-dev/${PEBBLE_SDK}/bin:$PATH
- touch pebble-dev/NO_TRACKING
- yes | pebble sdk install 3.8.2

env:
  global:
  - PEBBLE_SDK=pebble-sdk-4.0-linux64
