sudo: false

language: python

script:
- ./node_modules/.bin/gulp
- npm test

before_install:
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk2/${PEBBLE_SDK}.tar.gz -O PebbleSDK.tar.gz
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk/arm-cs-tools-ubuntu-universal.tar.gz
- mkdir pebble-dev
- tar -zxf PebbleSDK.tar.gz -C pebble-dev
- tar -zxf arm-cs-tools-ubuntu-universal.tar.gz -C pebble-dev/${PEBBLE_SDK}

install:
- nvm install 4.0
- pip install --install-option="--no-cython-compile" cython
- pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt
- npm install
- export PATH=$(pwd)/pebble-dev/${PEBBLE_SDK}/bin:$PATH
- touch pebble-dev/NO_TRACKING


env:
  global:
  - PEBBLE_SDK=PebbleSDK-3.2
